server:
  port: 8080
  servlet:
    context-path: /car-dealership

api:
  cepik:
    url: https://api.cepik.gov.pl/

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/car_dealership
    username: postgres
    password: postgres
    hikari:
      connectionTimeout: 20000
      minimumIdle: 10
      maximumPoolSize: 20
      idleTimeout: 300000
  security:
    enabled: false
    user:
      name: "test"
      password: "test"
  jpa:
    hibernate:
      ddl-auto: validate
      show-sql: true
      format-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mvc:
    hiddenmethod:
      filter:
        enabled: true